#!/usr/bin/env python3
import sys

def main():

    if len(sys.argv) == 1:
        print("please provide a file to run as a command line argument")
        sys.exit(1)
    program, labels = loadProgram(sys.argv[1])
    try:
        runProgram(program, labels)
    except IndexError:
        print("ERR: Program counter out of range")
        
def runProgram(program, labels):

    pc = 0
    registers = [0] * 12

    while True:
        incPc = True
        
        curOp  = program[pc]
        opCode = curOp[0]

        args = []
        for arg in curOp:
            args.append(resolveVal(arg, registers, labels))

        
        if opCode == "shn":
            print(args[1])

        if opCode == "sha":
            print(chr(args[1]))

        if opCode == "mov":
            registers[resolveReg(curOp[1])] = args[2]

        if opCode == "add":
            registers[resolveReg(curOp[1])] = args[2] + args[3]

        if opCode == "sub":
            registers[resolveReg(curOp[1])] = args[2] - args[3]
           
        if opCode == "jlt":
            if(args[2] < args[3]):
                pc = args[1]
                incPc = False

        if opCode == "jgt":
            if(args[2] > args[3]):
                pc = args[1]
                incPc = False

        if opCode == "jet":
            if(args[2] == args[3]):
                pc = args[1]
                incPc = False

        if opCode == "jmp":
            pc = args[1]
            incPc = False

        if opCode == "inp":
            if sys.stdin.isatty():
                print("> ", end="")
            try:
                registers[resolveReg(curOp[1])] = int(input())
            except EOFError:
                sys.exit()
        if opCode == "hlt":
            break    

        if(incPc):
            pc += 1

        if(pc == len(program)):
            pc = 0

        #print(curOp)
        #print(pc)
def resolveVal(val, reg, lab):
    if(val[0] == "#"):
        return int(val[1:])
    if(val[0] == "r"):
        return reg[resolveReg(val)]
    if(val in lab):
        return lab[val]
    #print("not resolved: " + val)
        
def resolveReg(reg):
    return int(reg[1:])
    
def loadProgram(filename):
    program = []
    labels  = {}
    with open(filename) as f:
        for line in f:
            noComLine = line.split(';')[0].strip()
            if noComLine:
                #print(noComLine[-1])
                if noComLine[-1] == ":":
                    labels[noComLine[:-1]] = len(program)
                else:
                    program.append(noComLine.split(" "))
    #print(program)
    return program, labels
    
if __name__ == "__main__":
    main()